image:
  pullPolicy: IfNotPresent
  repository: linuxserver/diskover
  tag: "2.0.1"

elasticsearch:
  image:
    pullPolicy: IfNotPresent
    repository: elasticsearch
    tag: "7.5.2"

python:
  image:
    pullPolicy: IfNotPresent
    repository: python
    tag: "3.10"

es_user: elasticsearch

image:
  pullPolicy: IfNotPresent
  repository: nextcloud
  tag: 28.0.2
nginx:
  image:
    pullPolicy: IfNotPresent
    repository: nginx
    tag: 1.23.3
useServiceNameForHost: false
